# Generated by Django 3.2.12 on 2022-05-12 07:56

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=250)),
                ('lName', models.CharField(max_length=250)),
                ('TimeJoin', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('Bio', models.TextField(null=True)),
                ('dateBrith', models.DateTimeField(null=True)),
                ('userName', models.CharField(max_length=60, null=sqlalchemy.sql.expression.false, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('websit', models.CharField(max_length=250, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
            ],
        ),
    ]
