# Generated by Django 3.2.12 on 2022-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('binary', 'binary')], default='male', max_length=100),
        ),
    ]
